src/main/java/lt/vtvpmc/exam/entities/Client.java
package lt.vtvpmc.exam.entities;

import java.util.Date;
import java.util.List;
import java.io.Serializable;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;


@Entity
public class Client implements Serializable {

	private static final long serialVersionUID = -2566315395134076434L;

	@Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE)
    private Long id;
    
    private String firstName;
    
    private String lastName;
    
	@Temporal(TemporalType.DATE)
	private Date birthDate;
    
    private String phoneNumber;
    
    private String clientType;

	@OneToMany(orphanRemoval = true, mappedBy = "client", fetch = FetchType.EAGER)
	private List<Inventory> clientInventory;
	
    public Client() {
    }

    public Client(String firstName, String lastName, Date birthDate, String phoneNumber, String clientType) {
        this.firstName = firstName;
        this.lastName = lastName;
        this.birthDate = birthDate;
        this.phoneNumber = phoneNumber;
        this.clientType = clientType;
    }
    
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public String getPhoneNumber() {
        return phoneNumber;
    }

    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

	public Date getBirthDate() {
		return birthDate;
	}

	public void setBirthDate(Date birthDate) {
		this.birthDate = birthDate;
	}



	public String getClientType() {
		return clientType;
	}

	public void setClientType(String clientType) {
		this.clientType = clientType;
	}

	public List<Inventory> getClientInventory() {
		return clientInventory;
	}

	public void setClientInventory(List<Inventory> clientInventory) {
		this.clientInventory = clientInventory;
	}
    
	public int inventoryNumber() {
		return clientInventory.size();
	}
	
	
}

src/main/java/lt/vtvpmc/exam/entities/Inventory.java
package lt.vtvpmc.exam.entities;

import java.util.Date;
import java.io.Serializable;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;


@Entity
public class Inventory implements Serializable {
    
	private static final long serialVersionUID = 6042924493204757773L;

	@Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE)
    private Long id;
    
    private String name;
    
    private double weight;
    
    private int sector;
    
	@Temporal(TemporalType.DATE)
    private Date date;
	
	@ManyToOne
	private Client client;

    public Inventory() {
    }

    public Inventory(String name, double weight, int sector, Date date) {
        this.name = name;
        this.weight = weight;
        this.sector = sector;
        this.date = date;
    }
    
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public double getWeight() {
		return weight;
	}

	public void setWeight(double weight) {
		this.weight = weight;
	}

	public int getSector() {
		return sector;
	}

	public void setSector(int sector) {
		this.sector = sector;
	}

	public Date getDate() {
		return date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

   
}

src/main/java/lt/vtvpmc/exam/ui/ClientListBean.java
package lt.vtvpmc.exam.ui;

import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.Query;
import lt.vtvpmc.exam.entities.Client;
import org.springframework.transaction.annotation.Transactional;

public class ClientListBean {
    
    @PersistenceContext
    private EntityManager entityManager;
    
    @Transactional(readOnly = true)
    public List<Client> getClientList() {
        Query q = entityManager.createQuery("select c from Client c");
        return q.getResultList();
    }
    
    @Transactional
    public void removeClient(Client client) {
        entityManager.remove(entityManager.merge(client));
    }
    
    @Transactional
    public String viewClient() {
        return "customerView";
    }
    
}

src/main/java/lt/vtvpmc/exam/ui/ClientViewBean.java
package lt.vtvpmc.exam.ui;

import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.Query;
import lt.vtvpmc.exam.entities.Client;
import lt.vtvpmc.exam.entities.Inventory;

import org.springframework.transaction.annotation.Transactional;

public class ClientViewBean {
    Client client;
	
	
    @PersistenceContext
    private EntityManager entityManager;
    
    @Transactional(readOnly = true)
    public List<Client> getInventoryList(Client currentClient) {
        Query q = entityManager.createQuery("select i from Inventory i where i.client like :currentClient")
        .setParameter("currentClient", currentClient);
        return q.getResultList();
    }

    @Transactional
    public void removeInventory(Inventory inventory) {
        entityManager.remove(entityManager.merge(inventory));
    }


	public Client getClient() {
		return client;
	}

	public void setClient(Client client) {
		this.client = client;
	}

	public EntityManager getEntityManager() {
		return entityManager;
	}

	public void setEntityManager(EntityManager entityManager) {
		this.entityManager = entityManager;
	}
    

    
}

src/main/java/lt/vtvpmc/exam/ui/InventoryReportBean.java
package lt.vtvpmc.exam.ui;

import java.util.ArrayList;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.Query;

import lt.vtvpmc.exam.entities.Client;
import lt.vtvpmc.exam.entities.Inventory;
import org.springframework.transaction.annotation.Transactional;

public class InventoryReportBean {
    
    @PersistenceContext
    private EntityManager entityManager;
    
    @Transactional(readOnly = true)
    public List<Client> topTotalWeight() {
       Query q = entityManager.createQuery("select c from Client c");
//       List<Client> newList = q.getResultList();
//       List<Client> topList = new ArrayList<>();
//       for (int i=0; newList.size() > i; i++) {
//    	   int tempSum = 0;
//    	   
//    	   for (int j=0; newList.get(i).getClientInventory().size() > j; j++) {
//    		   tempSum += newList.get(i).getClientInventory().get(j).getWeight();
//    	   }
//    	   if (topList.get(0) < top  ) {
//        	   topList.add(0, newList.get(i));   
//    	   }
//       }
        
        return q.getResultList();
    }
    
    @Transactional(readOnly = true)
    public List<Client> topTotalQuantity() {
        Query q = entityManager.createQuery("select c from Client c");
        return q.getResultList();
    }
    
    @Transactional(readOnly = true)
    public List<Client> topWeight() {
        Query q = entityManager.createQuery("select c from Client c");
        return q.getResultList();
    }
    
    @Transactional(readOnly = true)
    public List<Client> topQuantity() {
        Query q = entityManager.createQuery("select c from Client c");
        return q.getResultList();
    }

    
}

src/main/java/lt/vtvpmc/exam/ui/NewClientBean.java
package lt.vtvpmc.exam.ui;

import java.util.Date;

import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import lt.vtvpmc.exam.entities.Client;
import org.springframework.transaction.annotation.Transactional;



public class NewClientBean {
    
    @PersistenceContext
    private EntityManager entityManager;
    
    private String clientFirstName;
    private String clientLastName;
	private Date clientBirthDate;
    private String clientPhoneNumber;
    private String clientType;
    
    
    
    @Transactional
    public String save() {
        Client client = new Client(clientFirstName, clientLastName, clientBirthDate, clientPhoneNumber, clientType);
        entityManager.persist(client);
        return "main";
    }



	public EntityManager getEntityManager() {
		return entityManager;
	}



	public void setEntityManager(EntityManager entityManager) {
		this.entityManager = entityManager;
	}



	public String getClientFirstName() {
		return clientFirstName;
	}



	public void setClientFirstName(String clientFirstName) {
		this.clientFirstName = clientFirstName;
	}



	public String getClientLastName() {
		return clientLastName;
	}



	public void setClientLastName(String clientLastName) {
		this.clientLastName = clientLastName;
	}



	public Date getClientBirthDate() {
		return clientBirthDate;
	}



	public void setClientBirthDate(Date clientBirthDate) {
		this.clientBirthDate = clientBirthDate;
	}



	public String getClientPhoneNumber() {
		return clientPhoneNumber;
	}



	public void setClientPhoneNumber(String clientPhoneNumber) {
		this.clientPhoneNumber = clientPhoneNumber;
	}



	public String getClientType() {
		return clientType;
	}



	public void setClientType(String clientType) {
		this.clientType = clientType;
	}
    
  
    

    
}

src/main/java/lt/vtvpmc/exam/ui/NewInventoryBean.java
package lt.vtvpmc.exam.ui;

import java.util.Date;

import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import lt.vtvpmc.exam.entities.Inventory;
import org.springframework.transaction.annotation.Transactional;



public class NewInventoryBean {
    
    @PersistenceContext
    private EntityManager entityManager;
    
    private String inventoryName;  
    private double inventoryWeight;
    private int inventorySector;
    private Date inventoryDate;
	
    
    @Transactional
    public String save() {
        Inventory inventory = new Inventory(inventoryName, inventoryWeight, inventorySector, inventoryDate);
        entityManager.persist(inventory);
        return "customerView";
    }


	public EntityManager getEntityManager() {
		return entityManager;
	}


	public void setEntityManager(EntityManager entityManager) {
		this.entityManager = entityManager;
	}


	public String getInventoryName() {
		return inventoryName;
	}


	public void setInventoryName(String inventoryName) {
		this.inventoryName = inventoryName;
	}


	public double getInventoryWeight() {
		return inventoryWeight;
	}


	public void setInventoryWeight(double inventoryWeight) {
		this.inventoryWeight = inventoryWeight;
	}


	public int getInventorySector() {
		return inventorySector;
	}


	public void setInventorySector(int inventorySector) {
		this.inventorySector = inventorySector;
	}


	public Date getInventoryDate() {
		return inventoryDate;
	}


	public void setInventoryDate(Date inventoryDate) {
		this.inventoryDate = inventoryDate;
	}



    
}

src/main/webapp/addNewCustomer.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:p="http://primefaces.org/ui">
    <h:head>
        <title>Add New Customer</title>
        <h:outputStylesheet name="styles.css"/>
    </h:head>
    
    <h:body>
        <h:outputText value="Add New Customer" styleClass="pageTitle" />
        <br/>
        <h:form id="newCustomerForm">
            <h:panelGrid columns="3">
                <h:outputText value="Name:"/>
                <h:inputText id="clientName" value="#{newClientBean.clientFirstName}" required="true" requiredMessage="Please choose name" />
                <h:message for="clientName"/>
                
                <h:outputText value="Surname:"/>
                <h:inputText id="clientSurname" value="#{newClientBean.clientLastName}" required="true" requiredMessage="Please choose surname" />
                <h:message for="clientSurname"/>
                
                <h:outputText value="Date:"/>
                <p:calendar id="clientBirthDate" value="#{newClientBean.clientBirthDate}" required="true" 
                pattern="yyyy-MM-dd" readonlyInput="true" requiredMessage="Please choose a date" />
                <h:message for="clientBirthDate"/>
                
                <h:outputText value="Phone #:"/>
                <h:inputText id="clientPhoneNo" value="#{newClientBean.clientPhoneNumber}" required="true" requiredMessage="Please choose phone No" />
                <h:message for="clientPhoneNo"/>
                
                <h:outputText value="Client type:"/>
                <h:inputText id="clientType" value="#{newClientBean.clientType}" required="true" requiredMessage="Please choose client type" />
                <h:message for="clientType"/>
                
            </h:panelGrid>
            <h:commandButton action="#{newClientBean.save()}" value="Add"/>
        </h:form>
        <p:commandButton action="main" value="Back to main" />
    </h:body>
</html>

src/main/webapp/addNewInventory.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:p="http://primefaces.org/ui">
    <h:head>
        <title>Add New Inventory</title>
        <h:outputStylesheet name="styles.css"/>
    </h:head>
    
    <h:body>
        <h:outputText value="Add New Inventory" styleClass="pageTitle" />
        <br/>
        <h:form id="newInventoryForm">
            <h:panelGrid columns="3">
                <h:outputText value="Name:"/>
                <h:inputText id="iventoryName" value="#{newInventoryBean.inventoryName}" required="true" requiredMessage="Please choose name" />
                <h:message for="inventoryName"/>
                
                <h:outputText value="Weight:"/>
                <h:inputText id="inventoryWeight" value="#{newInventoryBean.inventoryWeight}" required="true" requiredMessage="Please choose weight" />
                <h:message for="inventoryWeight"/>

                <h:outputText value="Sector #:"/>
                <h:inputText id="inventorySector" value="#{newInventoryBean.inventorySector}" required="true" requiredMessage="Please choose sector" >
                	<f:validateLongRange minimum="1" maximum="40"  />
                </h:inputText>
                <h:message for="inventorySector"/>
                
                <h:outputText value="Date:"/>
                <p:calendar id="inventoryDate" value="#{newInventoryBean.inventoryDate}" required="true" 
                pattern="yyyy-MM-dd" readonlyInput="true" requiredMessage="Please choose a date" />
                <h:message for="inventoryDate"/>
                
            </h:panelGrid>
            <h:commandButton action="#{newInventoryBean.save()}" value="Add"/>
        </h:form>
        <p:commandButton action="main" value="Back to main" />
        
    </h:body>
</html>

src/main/webapp/customerView.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:p="http://primefaces.org/ui">
    <h:head>
        <title>View Customer</title>
        <h:outputStylesheet name="styles.css"/>
    </h:head>
    
     <h:body>
        <h:outputText value="View Customer" styleClass="pageTitle" />
        <br/>
     
        <h:form id="tableActionForm">
            <h:dataTable value="#{clientViewBean.client}" var="client">
                <h:column>
                    <f:facet name="header">
                        First Name
                    </f:facet>
                    <h:outputText value="#{client.firstName}"/>
                </h:column>
                <h:column>
                    <f:facet name="header">
                        Last Name
                    </f:facet>
                    <h:outputText value="#{client.lastName}"/>
                </h:column>
                <h:column>
                    <f:facet name="header">
                        Birth date
                    </f:facet>
                    <h:outputText value="#{client.birthDate}"/>
                </h:column>
                <h:column>
                    <f:facet name="header">
                        Phone number
                    </f:facet>
                    <h:outputText value="#{client.phoneNumber}"/>
                </h:column>
                <h:column>
                    <f:facet name="header">
                        Client type
                    </f:facet>
                    <h:outputText value="#{client.clientType}"/>
                </h:column>

            </h:dataTable>
        </h:form>
        <h:form id="actionForm">
            <h:commandButton id="addNewInventoryBtn" action="addNewInventory" value="Add New Inventory"/>
        </h:form>
		<br /><br />
		
        <h:form id="inventoryListForm">
            <h:dataTable value="#{clientViewBean.getInventoryList(client)}" var="invetory">
                <h:column>
                    <f:facet name="header">
                        Name
                    </f:facet>
                    <h:outputText value="#{inventory.name}"/>
                </h:column>
                <h:column>
                    <f:facet name="header">
                        Weight
                    </f:facet>
                    <h:outputText value="#{inventory.weight}"/>
                </h:column>
               <h:column>
                    <f:facet name="header">
                        Sector
                    </f:facet>
                    <h:outputText value="inventory.sector"/>
                </h:column>
                <h:column>
                    <f:facet name="header">
                        Date
                    </f:facet>
                    <h:outputText value="inventory.date"/>
                </h:column>
                <h:column>
                    <f:facet name="header">
                        Actions
                    </f:facet>
                    <h:commandLink actionListener="#{clientViewBean.removeInventory(inventory)}" value="Delete"/>
                </h:column>
            </h:dataTable>
        </h:form>
        <p:commandButton action="main" value="Back to main" />

    </h:body>
</html>

src/main/webapp/inventoryView.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:p="http://primefaces.org/ui">
    <h:head>
        <title>Inventory view</title>
        <h:outputStylesheet name="styles.css"/>
    </h:head>
    
    <h:body>
        <h:outputText value="Inventory view" styleClass="pageTitle" />
        <br/>
     
        <h:form id="topClientsInventoryForm">
            <h:dataTable value="#{inventoryReportBean.topTotalWeight()}" var="client">
                <h:column>
                    <f:facet name="header">
                        Top total weight - Client name
                    </f:facet>
                    <h:outputText value="#{client.firstName}"/>
                </h:column>		
            </h:dataTable>
            <h:dataTable value="#{inventoryReportBean.topTotalQuantity()}" var="client">
                <h:column>
                    <f:facet name="header">
                        Top total quantity - Client name
                    </f:facet>
                    <h:outputText value="#{client.firstName}"/>
                </h:column>		
            </h:dataTable>
            
            <h:dataTable value="#{inventoryReportBean.topWeight()}" var="client">
                <h:column>
                    <f:facet name="header">
                        Top weight - Client name
                    </f:facet>
                    <h:outputText value="#{client.firstName}"/>
                </h:column>		
            </h:dataTable>
            <h:dataTable value="#{inventoryReportBean.topQuantity()}" var="client">
                <h:column>
                    <f:facet name="header">
                        Top quantity - Client name
                    </f:facet>
                    <h:outputText value="#{client.firstName}"/>
                </h:column>		
            </h:dataTable>
 
        </h:form>
        
        <p:commandButton action="main" value="Back to main" />
    </h:body>
</html>

src/main/webapp/main.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:p="http://primefaces.org/ui">
    
    <h:head>
        <title>Main</title>
        <h:outputStylesheet name="styles.css"/>
    </h:head>

    <h:body>
        <h:form id="tableActionForm">
        	<h:outputText value="Main" styleClass="pageTitle" />
            <h:dataTable value="#{clientListBean.clientList}" var="client">
                <h:column>
                    <f:facet name="header">
                        First Name
                    </f:facet>
                    <h:outputText value="#{client.firstName}"/>
                </h:column>		
                <h:column>
                    <f:facet name="header">
                        Last Name
                    </f:facet>
                    <h:outputText value="#{client.lastName}"/>
                </h:column>
               <h:column>
                    <f:facet name="header">
                        Total inventory
                    </f:facet>
                    <h:outputText value="#{client.inventoryNumber()}"/>
                </h:column>
                <h:column>
                    <f:facet name="header">
                        Actions
                    </f:facet>
                    <h:commandLink action="customerView" value="View Customer"/>
                    <br/>	
                    <h:commandLink actionListener="#{clientListBean.removeClient(client)}" value="Delete"/>
                </h:column>
            </h:dataTable>
        </h:form>

        <h:form id="actionForm">
            <h:commandButton id="addNewCustomerBtn" action="addNewCustomer" value="Add New Customer"/>
        </h:form>

    </h:body>
</html>